// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}
