// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}
