// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function GetNotes(arg1:string):Promise<Array<main.Note>>;

export function GetTags():Promise<Array<main.Tag>>;

export function RemoveNote(arg1:string):Promise<main.CommandResult>;

export function UpdateNote(arg1:string,arg2:main.Note,arg3:string):Promise<main.CommandResult>;
